name: CharLib Tests
run-name: ${{ github.actor }} is testing CharLib

on: [push, pull_request]

jobs:

  Regression-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Install CharLib"
        run: |
          pip install -e .[docs]

      - name: "Run Tests"
        run: |
          pytest


