name: CharLib Tests
run-name: ${{ github.actor }} is testing CharLib

on: [push, pull_request]

jobs:

  Regression-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Install CharLib"
        run: |
          pip install -e .[docs]

      - name: "Run Tests"
        run: |
          pytest

  characterize_gf180mcu_osu_sc:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Install ngspice"
        run: |
          sudo apt update && sudo apt install -y libngspice0-dev

      - name: "Install CharLib"
        run: |
          pip install -e .[docs]

      - name: "Characterize"
        run: |
          ./test/pdks/gf180mcu_osu_sc/test_gf180mcu_osu_sc.sh

      - name: "Upload results"
        uses: actions/upload-artifact@v4
        with:
          name: characterization-results
          path: test/pdks/gf180mcu_osu_sc/gf180mcu_osu_sc_temp/gf180mcu_osu_sc_gp9t3v3/lib/gf180mcu_osu_sc_gp9t3v3_tt_25c.nldm.lib
